# frozen_string_literal: true

module Vellum
# * `ANONYMOUS` - ANONYMOUS
#  * `WORKSPACE_API_KEY` - WORKSPACE_API_KEY
#  * `ENVIRONMENT_API_KEY` - ENVIRONMENT_API_KEY
#  * `JWT` - JWT
#  * `SERVICE_TOKEN` - SERVICE_TOKEN
  class APIActorTypeEnum

    ANONYMOUS = "ANONYMOUS"
    WORKSPACE_API_KEY = "WORKSPACE_API_KEY"
    ENVIRONMENT_API_KEY = "ENVIRONMENT_API_KEY"
    JWT = "JWT"
    SERVICE_TOKEN = "SERVICE_TOKEN"

  end
end