# frozen_string_literal: true

require_relative "prompt_execution_meta"
require_relative "prompt_output"
require "json"

module Vellum
  # The successful response from the model containing all of the resolved values generated by the prompt.
  class FulfilledExecutePromptResponse
    attr_reader :meta, :raw, :execution_id, :outputs, :additional_properties

    # @param meta [PromptExecutionMeta]
    # @param raw [Hash{String => String}] The subset of the raw response from the model that the request opted into with `expand_raw`.
    # @param execution_id [String] The ID of the execution.
    # @param outputs [Array<PromptOutput>]
    # @param additional_properties [OpenStruct] Additional properties unmapped to the current class definition
    # @return [FulfilledExecutePromptResponse]
    def initialize(execution_id:, outputs:, meta: nil, raw: nil, additional_properties: nil)
      # @type [PromptExecutionMeta]
      @meta = meta
      # @type [Hash{String => String}] The subset of the raw response from the model that the request opted into with `expand_raw`.
      @raw = raw
      # @type [String] The ID of the execution.
      @execution_id = execution_id
      # @type [Array<PromptOutput>]
      @outputs = outputs
      # @type [OpenStruct] Additional properties unmapped to the current class definition
      @additional_properties = additional_properties
    end

    # Deserialize a JSON object to an instance of FulfilledExecutePromptResponse
    #
    # @param json_object [JSON]
    # @return [FulfilledExecutePromptResponse]
    def self.from_json(json_object:)
      struct = JSON.parse(json_object, object_class: OpenStruct)
      parsed_json = JSON.parse(json_object)
      if parsed_json["meta"].nil?
        meta = nil
      else
        meta = parsed_json["meta"].to_json
        meta = PromptExecutionMeta.from_json(json_object: meta)
      end
      raw = struct.raw
      execution_id = struct.execution_id
      outputs = parsed_json["outputs"].map do |v|
        v = v.to_json
        PromptOutput.from_json(json_object: v)
      end
      new(meta: meta, raw: raw, execution_id: execution_id, outputs: outputs, additional_properties: struct)
    end

    # Serialize an instance of FulfilledExecutePromptResponse to a JSON object
    #
    # @return [JSON]
    def to_json(*_args)
      { "meta": @meta, "raw": @raw, "execution_id": @execution_id, "outputs": @outputs }.to_json
    end

    # Leveraged for Union-type generation, validate_raw attempts to parse the given hash and check each fields type against the current object's property definitions.
    #
    # @param obj [Object]
    # @return [Void]
    def self.validate_raw(obj:)
      obj.meta.nil? || PromptExecutionMeta.validate_raw(obj: obj.meta)
      obj.raw&.is_a?(Hash) != false || raise("Passed value for field obj.raw is not the expected type, validation failed.")
      obj.execution_id.is_a?(String) != false || raise("Passed value for field obj.execution_id is not the expected type, validation failed.")
      obj.outputs.is_a?(Array) != false || raise("Passed value for field obj.outputs is not the expected type, validation failed.")
    end
  end
end
