# frozen_string_literal: true
require_relative "prompt_execution_meta"
require_relative "prompt_output"
require "ostruct"
require "json"

module Vellum
# The successful response from the model containing all of the resolved values
#  generated by the prompt.
  class FulfilledExecutePromptResponse
  # @return [Vellum::PromptExecutionMeta] 
    attr_reader :meta
  # @return [Hash{String => Object}] The subset of the raw response from the model that the request opted into with
#  `expand_raw`.
    attr_reader :raw
  # @return [String] The ID of the execution.
    attr_reader :execution_id
  # @return [Array<Vellum::PromptOutput>] 
    attr_reader :outputs
  # @return [OpenStruct] Additional properties unmapped to the current class definition
    attr_reader :additional_properties
  # @return [Object] 
    attr_reader :_field_set
    protected :_field_set

    OMIT = Object.new

    # @param meta [Vellum::PromptExecutionMeta] 
    # @param raw [Hash{String => Object}] The subset of the raw response from the model that the request opted into with
#  `expand_raw`.
    # @param execution_id [String] The ID of the execution.
    # @param outputs [Array<Vellum::PromptOutput>] 
    # @param additional_properties [OpenStruct] Additional properties unmapped to the current class definition
    # @return [Vellum::FulfilledExecutePromptResponse]
    def initialize(meta: OMIT, raw: OMIT, execution_id:, outputs:, additional_properties: nil)
      @meta = meta if meta != OMIT
      @raw = raw if raw != OMIT
      @execution_id = execution_id
      @outputs = outputs
      @additional_properties = additional_properties
      @_field_set = { "meta": meta, "raw": raw, "execution_id": execution_id, "outputs": outputs }.reject do | _k, v |
  v == OMIT
end
    end
# Deserialize a JSON object to an instance of FulfilledExecutePromptResponse
    #
    # @param json_object [String] 
    # @return [Vellum::FulfilledExecutePromptResponse]
    def self.from_json(json_object:)
      struct = JSON.parse(json_object, object_class: OpenStruct)
      parsed_json = JSON.parse(json_object)
      unless parsed_json["meta"].nil?
        meta = parsed_json["meta"].to_json
        meta = Vellum::PromptExecutionMeta.from_json(json_object: meta)
      else
        meta = nil
      end
      raw = parsed_json["raw"]
      execution_id = parsed_json["execution_id"]
      outputs = parsed_json["outputs"]&.map do | item |
  item = item.to_json
  Vellum::PromptOutput.from_json(json_object: item)
end
      new(
        meta: meta,
        raw: raw,
        execution_id: execution_id,
        outputs: outputs,
        additional_properties: struct
      )
    end
# Serialize an instance of FulfilledExecutePromptResponse to a JSON object
    #
    # @return [String]
    def to_json
      @_field_set&.to_json
    end
# Leveraged for Union-type generation, validate_raw attempts to parse the given
#  hash and check each fields type against the current object's property
#  definitions.
    #
    # @param obj [Object] 
    # @return [Void]
    def self.validate_raw(obj:)
      obj.meta.nil? || Vellum::PromptExecutionMeta.validate_raw(obj: obj.meta)
      obj.raw&.is_a?(Hash) != false || raise("Passed value for field obj.raw is not the expected type, validation failed.")
      obj.execution_id.is_a?(String) != false || raise("Passed value for field obj.execution_id is not the expected type, validation failed.")
      obj.outputs.is_a?(Array) != false || raise("Passed value for field obj.outputs is not the expected type, validation failed.")
    end
  end
end