# frozen_string_literal: true

module Vellum
# * `INVALID_REQUEST` - INVALID_REQUEST
#  * `INVALID_INPUTS` - INVALID_INPUTS
#  * `PROVIDER_ERROR` - PROVIDER_ERROR
#  * `PROVIDER_CREDENTIALS_AVAILABLE` - PROVIDER_CREDENTIALS_UNAVAILABLE
#  * `REQUEST_TIMEOUT` - REQUEST_TIMEOUT
#  * `INTERNAL_SERVER_ERROR` - INTERNAL_SERVER_ERROR
#  * `USER_DEFINED_ERROR` - USER_DEFINED_ERROR
#  * `WORKFLOW_CANCELLED` - WORKFLOW_CANCELLED
  class VellumErrorCodeEnum

    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_INPUTS = "INVALID_INPUTS"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    PROVIDER_CREDENTIALS_AVAILABLE = "PROVIDER_CREDENTIALS_AVAILABLE"
    REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    USER_DEFINED_ERROR = "USER_DEFINED_ERROR"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"

  end
end