# frozen_string_literal: true

module Vellum
# * `INVALID_WORKFLOW` - INVALID_WORKFLOW
#  * `INVALID_INPUTS` - INVALID_INPUTS
#  * `INVALID_OUTPUTS` - INVALID_OUTPUTS
#  * `INVALID_STATE` - INVALID_STATE
#  * `INVALID_CODE` - INVALID_CODE
#  * `INVALID_TEMPLATE` - INVALID_TEMPLATE
#  * `INTERNAL_ERROR` - INTERNAL_ERROR
#  * `PROVIDER_CREDENTIALS_UNAVAILABLE` - PROVIDER_CREDENTIALS_UNAVAILABLE
#  * `INTEGRATION_CREDENTIALS_UNAVAILABLE` - INTEGRATION_CREDENTIALS_UNAVAILABLE
#  * `PROVIDER_ERROR` - PROVIDER_ERROR
#  * `PROVIDER_QUOTA_EXCEEDED` - PROVIDER_QUOTA_EXCEEDED
#  * `USER_DEFINED_ERROR` - USER_DEFINED_ERROR
#  * `WORKFLOW_CANCELLED` - WORKFLOW_CANCELLED
#  * `WORKFLOW_TIMEOUT` - WORKFLOW_TIMEOUT
#  * `NODE_CANCELLED` - NODE_CANCELLED
#  * `NODE_TIMEOUT` - NODE_TIMEOUT
#  * `NODE_EXECUTION` - NODE_EXECUTION
  class VellumSdkErrorCodeEnum

    INVALID_WORKFLOW = "INVALID_WORKFLOW"
    INVALID_INPUTS = "INVALID_INPUTS"
    INVALID_OUTPUTS = "INVALID_OUTPUTS"
    INVALID_STATE = "INVALID_STATE"
    INVALID_CODE = "INVALID_CODE"
    INVALID_TEMPLATE = "INVALID_TEMPLATE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    PROVIDER_CREDENTIALS_UNAVAILABLE = "PROVIDER_CREDENTIALS_UNAVAILABLE"
    INTEGRATION_CREDENTIALS_UNAVAILABLE = "INTEGRATION_CREDENTIALS_UNAVAILABLE"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    PROVIDER_QUOTA_EXCEEDED = "PROVIDER_QUOTA_EXCEEDED"
    USER_DEFINED_ERROR = "USER_DEFINED_ERROR"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"
    WORKFLOW_TIMEOUT = "WORKFLOW_TIMEOUT"
    NODE_CANCELLED = "NODE_CANCELLED"
    NODE_TIMEOUT = "NODE_TIMEOUT"
    NODE_EXECUTION = "NODE_EXECUTION"

  end
end