# frozen_string_literal: true

module Vellum
# * `INVALID_REQUEST` - INVALID_REQUEST
#  * `INVALID_INPUTS` - INVALID_INPUTS
#  * `PROVIDER_ERROR` - PROVIDER_ERROR
#  * `REQUEST_TIMEOUT` - REQUEST_TIMEOUT
#  * `INTERNAL_SERVER_ERROR` - INTERNAL_SERVER_ERROR
#  * `USER_DEFINED_ERROR` - USER_DEFINED_ERROR
  class VellumErrorCodeEnum

    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_INPUTS = "INVALID_INPUTS"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    USER_DEFINED_ERROR = "USER_DEFINED_ERROR"

  end
end