# frozen_string_literal: true

module Vellum
# * `STRING` - STRING
#  * `NUMBER` - NUMBER
#  * `JSON` - JSON
#  * `CHAT_HISTORY` - CHAT_HISTORY
#  * `SEARCH_RESULTS` - SEARCH_RESULTS
#  * `ERROR` - ERROR
#  * `ARRAY` - ARRAY
#  * `FUNCTION_CALL` - FUNCTION_CALL
#  * `IMAGE` - IMAGE
#  * `AUDIO` - AUDIO
#  * `DOCUMENT` - DOCUMENT
#  * `NULL` - NULL
#  * `THINKING` - THINKING
  class VellumVariableType

    STRING = "STRING"
    NUMBER = "NUMBER"
    JSON_ = "JSON"
    CHAT_HISTORY = "CHAT_HISTORY"
    SEARCH_RESULTS = "SEARCH_RESULTS"
    ERROR = "ERROR"
    ARRAY = "ARRAY"
    FUNCTION_CALL = "FUNCTION_CALL"
    IMAGE = "IMAGE"
    AUDIO = "AUDIO"
    DOCUMENT = "DOCUMENT"
    NULL = "NULL"
    THINKING = "THINKING"

  end
end