# frozen_string_literal: true

module Vellum
# * `UNKNOWN` - UNKNOWN
#  * `DEPENDENCIES_FAILED` - DEPENDENCIES_FAILED
#  * `NO_USAGE_CALCULATED` - NO_USAGE_CALCULATED
#  * `INTERNAL_SERVER_ERROR` - INTERNAL_SERVER_ERROR
  class WorkflowExecutionUsageCalculationErrorCodeEnum

    UNKNOWN = "UNKNOWN"
    DEPENDENCIES_FAILED = "DEPENDENCIES_FAILED"
    NO_USAGE_CALCULATED = "NO_USAGE_CALCULATED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

  end
end