# frozen_string_literal: true

module Vellum
# * `WORKFLOW_INITIALIZATION` - WORKFLOW_INITIALIZATION
#  * `WORKFLOW_CANCELLED` - WORKFLOW_CANCELLED
#  * `PROVIDER_CREDENTIALS_UNAVAILABLE` - PROVIDER_CREDENTIALS_UNAVAILABLE
#  * `INTEGRATION_CREDENTIALS_UNAVAILABLE` - INTEGRATION_CREDENTIALS_UNAVAILABLE
#  * `NODE_EXECUTION_COUNT_LIMIT_REACHED` - NODE_EXECUTION_COUNT_LIMIT_REACHED
#  * `INTERNAL_SERVER_ERROR` - INTERNAL_SERVER_ERROR
#  * `NODE_EXECUTION` - NODE_EXECUTION
#  * `NODE_CANCELLED` - NODE_CANCELLED
#  * `LLM_PROVIDER` - LLM_PROVIDER
#  * `INVALID_TEMPLATE` - INVALID_TEMPLATE
#  * `INVALID_INPUTS` - INVALID_INPUTS
#  * `PROVIDER_QUOTA_EXCEEDED` - PROVIDER_QUOTA_EXCEEDED
#  * `USER_DEFINED_ERROR` - USER_DEFINED_ERROR
  class WorkflowExecutionEventErrorCode

    WORKFLOW_INITIALIZATION = "WORKFLOW_INITIALIZATION"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"
    PROVIDER_CREDENTIALS_UNAVAILABLE = "PROVIDER_CREDENTIALS_UNAVAILABLE"
    INTEGRATION_CREDENTIALS_UNAVAILABLE = "INTEGRATION_CREDENTIALS_UNAVAILABLE"
    NODE_EXECUTION_COUNT_LIMIT_REACHED = "NODE_EXECUTION_COUNT_LIMIT_REACHED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    NODE_EXECUTION = "NODE_EXECUTION"
    NODE_CANCELLED = "NODE_CANCELLED"
    LLM_PROVIDER = "LLM_PROVIDER"
    INVALID_TEMPLATE = "INVALID_TEMPLATE"
    INVALID_INPUTS = "INVALID_INPUTS"
    PROVIDER_QUOTA_EXCEEDED = "PROVIDER_QUOTA_EXCEEDED"
    USER_DEFINED_ERROR = "USER_DEFINED_ERROR"

  end
end